<?php 
    $this->headScript()->offsetSetFile(1, $this->baseUrl().'/assets/js/script.js', 'text/javascript');
    
    $this->headLink()->appendStylesheet($this->baseUrl().'/assets/css/views/normalize.css');
    $this->headLink()->appendStylesheet($this->baseUrl().'/assets/css/views/competition.css');
?>

<div id="fb_wrapper" class="competition">         
            <div class="leaderboard scoreList">
                <ul>
                    <?php 
                        foreach($this->scoreList as $playerScore){
                            if(isset($playerScore['twitterhandle']) && !empty($playerScore['twitterhandle'])){
                                echo '<li><a href="https://twitter.com/' . $playerScore['twitterhandle'] . '" title="' . $playerScore['twitterhandle'] . '" target="_blank" class="username">' . $playerScore['twitterhandle'] . '</a><span class="userscore">' . $playerScore['playerScore'] . '</span></li>';
                            }
                            else{
                                echo '<li><a href="https://twitter.com/tmwagency" title="' . $playerScore['firstname'] . ' ' . $playerScore['lastname'][0] . '" target="_blank" class="username">' . $playerScore['firstname'] . ' ' . $playerScore['lastname'][0] . '</a><span class="userscore">' . $playerScore['playerScore'] . '</span></li>';   
                            }
                        }
                    ?>
                </ul>
            </div>
           
            <div class="live-feed">

            </div>
            <div class="twiterFeed tweets">
                <ul>
                    <?php
                        foreach ($this->twitterFeed as $tweet) {
                            echo '<li>' . $tweet['text']. '</li>';
                        }
                    ?>                      
                </ul>     
            </div>
            <div class="now-playing playerDetails">
                <?php
                    if(isset($this->playerDetails['twitterhandle']) && !empty($this->playerDetails['twitterhandle'])){
                        echo '<img src="' . $this->playerDetails['playerTwitterImg'] . '" alt="' . $this->playerDetails['twitterhandle'] . '" />';
                        echo '<div class="now-playing-name"><a href="https://twitter.com/' . $this->playerDetails['twitterhandle'] . '" title="' . $this->playerDetails['twitterhandle'] . '" target="_blank">' . $this->playerDetails['twitterhandle'] . '</a></div>';               
                    }
                    else{
                        echo '<img src="' . $this->playerDetails['playerTwitterImg'] . '" alt="' . $this->playerDetails['firstname'] . ' ' . $this->playerDetails['lastname'][0] . '" />';
                        echo '<div class="now-playing-name"><a href="https://twitter.com/tmwagency" title="' . $this->playerDetails['firstname'] . ' ' . $this->playerDetails['lastname'][0] . '" target="_blank">' . $this->playerDetails['firstname'] . ' ' . $this->playerDetails['lastname'][0] . '</a></div>';   
                    }
                ?>
            </div>
            <div class="score">
                <?php echo $this->playerDetails['playerScore'] ?>
            </div> 
    <div class="clear"></div>
</div>
