<?php 
    $this->headScript()->offsetSetFile(3, $this->baseUrl().'/assets/js/jquery.jscrollpane.min.js', 'text/javascript');
    $this->headScript()->offsetSetFile(4, $this->baseUrl().'/assets/js/jquery.mousewheel.js', 'text/javascript');
    $this->headScript()->offsetSetFile(5, $this->baseUrl().'/assets/js/feed-script.js', 'text/javascript'); 
    
    $this->headLink()->appendStylesheet($this->baseUrl().'/assets/css/views/normalize.css');
    $this->headLink()->appendStylesheet($this->baseUrl().'/assets/css/views/competition.css');
    $this->headLink()->appendStylesheet($this->baseUrl().'/assets/css/views/jquery.jscrollpane.css');
    $this->headLink()->appendStylesheet($this->baseUrl().'/assets/css/views/feedpage.css');
?>

<div id="fb_wrapper" class="competition feedPage">
            <div class="introCopy">
                <p>To celebrate TMW’s recent move to Soho, clients were invited to test-drive a range of emerging technologies via a special installation created for the event.  
                Connecting RFID tagging and arduino electronics to social media through one giant TMW-shaped hoop and wire game, clients were invited to take a virtual trip around TMW’s 
                swanky new offices by getting from one end of the copper-pipe lettering to the other.</p>
                <p><a href="http://www.tmw.co.uk" title="Find out how innovative technologies can work for your business." target="_blank">Find out how innovative technologies can work for your business.</a></p>
            </div>
            <div class="leaderboard scoreList">
                <p>Client with the fastest time got £500 to give to their chosen charity.</p>
                <ul>
                    <?php
                        $playerCount = 0;
                        foreach($this->scoreList as $playerScore){
                            if(isset($playerScore['twitterhandle']) && !empty($playerScore['twitterhandle'])){
                                echo '<li class="player' . $playerCount . '"><a href="https://twitter.com/' . $playerScore['twitterhandle'] . '" title="@' . $playerScore['twitterhandle'] . '" target="_blank" class="username">@' . $playerScore['twitterhandle'] . '</a><span class="userscore">' . $playerScore['playerProgress'] . '%</span><span class="usertime">(' . $playerScore['playerTime'] . ')</span></li>';
                            }
                            else{
                                echo '<li class="player' . $playerCount . '"><a href="https://twitter.com/tmwagency" title="' . $playerScore['firstname'] . ' ' . $playerScore['lastname'][0] . '" target="_blank" class="username">' . $playerScore['firstname'] . ' ' . $playerScore['lastname'][0] . '</a><span class="userscore">' . $playerScore['playerProgress'] . '%</span><span class="usertime">(' . $playerScore['playerTime'] . ')</span></li>';   
                            }
                            $playerCount++;
                        }
                    ?>
                </ul>
            </div>
            
            <div class="twiterFeed tweets">
                <p>Steady Eddies or Shakin’ Stevens. All the buzz captured on Twitter.</p>
                <ul>
                    <?php
                        foreach ($this->twitterFeed as $tweet) {
                            echo '<li>' . $tweet['text']. '</li>';
                        }
                    ?>                      
                </ul>     
            </div>
            <div class="playerGallery">
                <p>Photos of contestants captured and posted on their Twitter feed the moment they touched the wire.</p>
                <div class="scroll-pane">
                <?php
                    for ($i = 1; $i <= 10; $i++) {
                        if(isset($this->playerDetails['twitterhandle']) && !empty($this->playerDetails['twitterhandle'])){
                            echo '<div class="now-playing playerDetails">';
                            echo '<div class="now-playing-img"><img src="' . $this->playerDetails['playerTwitterImg'] . '" alt="@' . $this->playerDetails['twitterhandle'] . '" /><img src="' . $this->baseUrl(). '/assets/img/competition/skrews.png" class="skrews" /></div>';
                            echo '<div class="now-playing-name"><a href="https://twitter.com/' . $this->playerDetails['twitterhandle'] . '" title="@' . $this->playerDetails['twitterhandle'] . '" target="_blank">@' . $this->playerDetails['twitterhandle'] . '</a></div>';               
                            echo '</div>';                        
                        }
                        else{
                            echo '<div class="now-playing playerDetails">';
                            echo '<div class="now-playing-img"><img src="' . $this->playerDetails['playerTwitterImg'] . '" alt="' . $this->playerDetails['firstname'] . ' ' . $this->playerDetails['lastname'][0] . '" /><img src="' . $this->baseUrl(). '/assets/img/competition/skrews.png" class="skrews" /></div>';
                            echo '<div class="now-playing-name"><a href="https://twitter.com/tmwagency" title="' . $this->playerDetails['firstname'] . ' ' . $this->playerDetails['lastname'][0] . '" target="_blank">' . $this->playerDetails['firstname'] . ' ' . $this->playerDetails['lastname'][0] . '</a></div>';   
                            echo '</div>';                        
                        }
                    }
                ?>
                </div>              
            </div>
    <div class="clear"></div>
</div>