<div id="fb_wrapper" class="competition">
    <div class="header">
        <?php
            if(!empty($this->contents['displayImage'])) {
                echo '<img class="adImage" src="/assets/img/competition/wire-game/addImage.jpg" alt="'.$this->facebookShare['title'].'" />';
                echo '<div class="sideHeaders">';
            }
            if(!empty($this->contents['headerText1'])) {
                echo '<h1>'.$this->contents['headerText1'].'</h1>';
            }
            if(!empty($this->contents['headerText2'])) {
                echo '<h2>'.$this->contents['headerText2'].'</h2>';
            }
            if(!empty($this->contents['displayImage'])) {
                echo '</div>';
            }
        ?>
    </div>
    <div class="contentsHolderOuter">
        <div class="contentsHolder">
            <div id="fb_content_copy">
                <?php
                    if(!empty($this->contents['introText'])) {
                        echo '<p>'.$this->contents['introText'].'</p>';
                    }
                ?>
            </div> 
            <div class="playerDetails">
                <h3>Loaded by the database user details</h3>
                <?php
                    echo '<p><a href="https://twitter.com/' . $this->playerDetails['twitterhandle'] . '" title="' . $this->playerDetails['firstname'] . ' ' . $this->playerDetails['lastname'] . ' Tweeter" target="_blank">' . $this->playerDetails['firstname'] . ' ' . $this->playerDetails['lastname'] . '<img src="' . $this->playerDetails['playerTwitterImg'] . '" alt="' . $this->playerDetails['twitterhandle'] . '" /></a></p>';
                ?>       
            </div>
            <div class="scoreList">
                <h3>Loaded by the database user scores</h3>
                <ul>
                    <?php 
                        foreach($this->scoreList as $playerScore){
                            echo '<li><a href="https://twitter.com/' . $playerScore['twitterhandle'] . '" title="' . $playerScore['firstname'] . ' ' . $playerScore['lastname'] . ' Tweeter" target="_blank">' . $playerScore['firstname'] . ' ' . $playerScore['lastname'] . '</a> scored ' . $playerScore['playerScore'] . ' (' . $playerScore['playerProgress'] . '%)</li>';
                        }
                    ?>
                </ul>
            </div>
            <div class="gameGallery">
                <h3>Photogallery</h3>     
            </div>
        </div>  
    </div>
</div>
