<div id="fb_wrapper" class="competition">
    <div class="header">
        <?php
            if(!empty($this->contents['displayImage'])) {
                echo '<img class="adImage" src="/assets/img/competition/wire-game/addImage.jpg" alt="'.$this->facebookShare['title'].'" />';
                echo '<div class="sideHeaders">';
            }
            if(!empty($this->contents['headerText1'])) {
                echo '<h1>'.$this->contents['headerText1'].'</h1>';
            }
            if(!empty($this->contents['headerText2'])) {
                echo '<h2>'.$this->contents['headerText2'].'</h2>';
            }
            if(!empty($this->contents['displayImage'])) {
                echo '</div>';
            }
        ?>
    </div>
    <div class="contentsHolderOuter">
        <div class="contentsHolder">
            <div id="fb_content_copy">
                <?php
                    if(!empty($this->contents['introText'])) {
                        echo '<p>'.$this->contents['introText'].'</p>';
                    }
                    if(!empty($this->contents['introVideo'])) {
                        echo '<iframe width="551" height="311" frameborder="0" allowfullscreen="" src="http://www.youtube.com/embed/'.$this->contents['introVideo'].'?rel=0&wmode=transparent"></iframe>';
                    }
                ?>
            </div>
            <div id="fb_form">

                <form method="post" action="/competition/<?php echo $this->facebookShare['campaign']; ?>/index?ajax=true" id="fbForm" enctype="multipart/form-data" accept-charset="utf-8" rel="1">
                    <div class="startingField">
                    <?php
                        $currentElement = 0;
                        
                        foreach($this->formElements as $formElement)
                        {
                            if($formElement['elementVisibility'])
                            {   
                                if($formElement['elementType'] == 'File')
                                {
                                    echo $this->form->getElement('fbimage')->render();
                                    echo '<dd id="BrowserVisible"><input type="text" id="FileField" /><span id="fileBtnSpan" class="button">Browse</span></dd>';
                                }
                                else if($formElement['elementType'] == 'Email')
                                {
                                    echo $this->form->getElement('playerEmail')->render();
                                }
                                else if($formElement['elementType'] == 'Textarea')
                                {
                                    echo  '<div class="textAreaHolder">';
                                    echo $this->form->getElement($formElement['elementName'])->render();
                                    echo  '</div>';
                                }
                                else if($formElement['elementType'] == 'Checkbox')
                                {
                                    echo  '<div class="checkboxHolder">';
                                    echo $this->form->getElement($formElement['elementName'])->render();
                                    echo  '</div>';
                                }
                                else
                                {
                                    echo $this->form->getElement($formElement['elementName'])->render();
                                }
                                
                                if ($currentElement == 0)
                                {
                                    echo '</div><div class="fieldsListing"><h3>Your Details</h3><span class="reqCopy">(*Required)</span>';
                                }
                                $currentElement++;
                            }
                        }
                    ?> 
                        <div class="fbTermsConditionsHolder checkboxHolder">
                            <dd>
                                <input type="hidden" value="" name="fbTermsConditions" />
                                <input type="checkbox" message="Please agree to the terms and conditions" value="1" id="fbTermsConditions" name="fbTermsConditions" />
                            </dd>
                            <p class="description">I accept the <a href="<?php echo $this->contents['tncText']; ?>" title="Terms & Conditions" target="_blank">Terms & Conditions</a> & have read the <a href="<?php echo $this->contents['policyText']; ?>" title="Privacy Policy" target="_blank">Privacy Policy</a>.</p>
                            <input type="hidden" name="campaignName" id="campaignName" value="<?php echo $this->facebookShare['campaignName']?>" />
                            <input type="hidden" name="campaign" id="campaign" value="<?php echo $this->facebookShare['campaign']?>" />
                        </div>
                        <?php echo $this->form->getElement('submitBtn')->setLabel('Submit')->render(); ?>
                    </div> 
                </form>
            </div>
            <div class="smoIcons">
                <h4>Tell Your Friends</h4>
                <ul>
                    <li>
                        <a target="_blank" title="Share This on Facebook" href="http://www.facebook.com/sharer.php?u=<?php echo urlencode($this->facebookShare['url']); ?>&amp;t=<?php echo urlencode($this->facebookShare['title']); ?>" class="smoIcon fbIcon"></a>
                    </li>
                    <li>
                        <a target="_blank" title="Tweet This" href="http://twitter.com/share?text=<?php echo urlencode($this->facebookShare['title']); ?>&amp;url=<?php echo urlencode($this->facebookShare['url']); ?>" class="smoIcon tweetIcon"></a>
                    </li>
                    <li>
                        <a target="_blank" title="Share This on Google+" href="https://plus.google.com/share?url=<?php echo urlencode($this->facebookShare['url']); ?>" class="smoIcon gplusIcon"></a>
                    </li>
                </ul>
            </div>
        </div>  
    </div>
</div>
