<div id="fb_wrapper" class="competition">
    <div class="header">
        <?php
            if(!empty($this->contents['displayImage'])) {
                echo '<img class="adImage" src="/assets/img/competition/wire-game/addImage.jpg" alt="'.$this->facebookShare['title'].'" />';
                echo '<div class="sideHeaders">';
            }
            if(!empty($this->contents['headerText1'])) {
                echo '<h1>'.$this->contents['headerText1'].'</h1>';
            }
            if(!empty($this->contents['headerText2'])) {
                echo '<h2>'.$this->contents['headerText2'].'</h2>';
            }
            if(!empty($this->contents['displayImage'])) {
                echo '</div>';
            }
        ?>
    </div>
    <div class="contentsHolderOuter">
        <div class="contentsHolder">
            <div id="fb_content_copy">
                <?php
                    if(!empty($this->contents['introText'])) {
                        echo '<p>'.$this->contents['introText'].'</p>';
                    }
                ?>
            </div> 
            
            <div class="videoContainer">
                <h3>Controllable by js video</h3>
               
            </div>
            <div class="playerDetails">
                <h3>Loaded by the database user details</h3>
                <?php
                    if(isset($this->playerDetails['twitterhandle']) && !empty($this->playerDetails['twitterhandle'])){
                        echo '<p><a href="https://twitter.com/' . $this->playerDetails['twitterhandle'] . '" title="' . $this->playerDetails['twitterhandle'] . '" target="_blank">' . $this->playerDetails['twitterhandle'] . '<img src="' . $this->playerDetails['playerTwitterImg'] . '" alt="' . $this->playerDetails['twitterhandle'] . '" /></a></p>';               
                    }
                    else{
                        echo '<p><a href="https://twitter.com/tmwagency" title="' . $this->playerDetails['firstname'] . ' ' . $this->playerDetails['lastname'][0] . '" target="_blank">' . $this->playerDetails['firstname'] . ' ' . $this->playerDetails['lastname'][0] . '<img src="' . $this->playerDetails['playerTwitterImg'] . '" alt="' . $this->playerDetails['firstname'] . ' ' . $this->playerDetails['lastname'][0] . '" /></a></p>';   
                    }
                ?>       
            </div>
            <div class="scoreList">
                <h3>Loaded by the database user scores</h3>
                <ul>
                    <?php 
                        foreach($this->scoreList as $playerScore){
                            if(isset($playerScore['twitterhandle']) && !empty($playerScore['twitterhandle'])){
                                echo '<li><a href="https://twitter.com/' . $playerScore['twitterhandle'] . '" title="' . $playerScore['twitterhandle'] . '" target="_blank">' . $playerScore['twitterhandle'] . '</a> scored ' . $playerScore['playerScore'] . ' (' . $playerScore['playerProgress'] . '%)</li>';
                            }
                            else{
                                echo '<li><a href="https://twitter.com/tmwagency" title="' . $playerScore['firstname'] . ' ' . $playerScore['lastname'][0] . '" target="_blank">' . $playerScore['firstname'] . ' ' . $playerScore['lastname'][0] . '</a> scored ' . $playerScore['playerScore'] . ' (' . $playerScore['playerProgress'] . '%)</li>';   
                            }
                        }
                    ?>
                </ul>
            </div>
            <div class="twiterFeed">
                <h3>Loaded the tweets from the user timeline</h3>
                <ul>
                    <?php
                        foreach ($this->twitterFeed as $tweet) {
                            echo '<li>' . $tweet['text']. '</li>';
                        }
                    ?>                      
                </ul>     
            </div>
        </div>  
    </div>
</div>
