<div id="fb_wrapper" class="competition">
    <div class="header">
        <?php
            if(!empty($this->contents['displayImage'])) {
                echo '<img class="adImage" src="/assets/img/competition/wire-game/addImage.jpg" alt="'.$this->facebookShare['title'].'" />';
                echo '<div class="sideHeaders">';
            }
            if(!empty($this->contents['headerText1'])) {
                echo '<h1>'.$this->contents['headerText1'].'</h1>';
            }
            if(!empty($this->contents['headerText2'])) {
                echo '<h2>'.$this->contents['headerText2'].'</h2>';
            }
            if(!empty($this->contents['displayImage'])) {
                echo '</div>';
            }
        ?>
    </div>
    <div class="contentsHolderOuter">
        <div class="contentsHolder">
            <div id="fb_content_copy">
                <?php
                    if(!empty($this->contents['introText'])) {
                        echo '<p>'.$this->contents['introText'].'</p>';
                    }
                    if(!empty($this->contents['introVideo'])) {
                        echo '<iframe width="551" height="311" frameborder="0" allowfullscreen="" src="http://www.youtube.com/embed/'.$this->contents['introVideo'].'?rel=0&wmode=transparent"></iframe>';
                    }
                ?>
            </div>
            <div class="scoreList">
                <ul>
                    <?php 
                        foreach($this->scoreList as $playerScore){
                            echo '<li><a href="https://twitter.com/' . $playerScore['tweeter'] . '" title="' . $playerScore['firstname'] . ' ' . $playerScore['lastname'] . ' Tweeter" target="_blank">' . $playerScore['firstname'] . ' ' . $playerScore['lastname'] . '</a> scored ' . $playerScore['playerScore'] . ' (' . $playerScore['playerProgress'] . '%)</li>';
                        }
                    ?>
                </ul>
            </div>    
    </div>
</div>
