<?php 
    $this->headScript()->offsetSetFile(1, $this->baseUrl().'/assets/js/jquery.form.js', 'text/javascript');
    $this->headScript()->offsetSetFile(2, $this->baseUrl().'/assets/js/register.js', 'text/javascript');
    
    $this->headLink()->appendStylesheet($this->baseUrl().'/assets/css/views/register.css');
?>

<div id="fb_wrapper" class="competition registerPage">
    <div class="header">        
        <a href="/competition/<?php echo $this->facebookShare['campaign']; ?>/rsvp" title="">
            <img src="/assets/img/competition/logo.jpg" alt="TMW" />
        </a>
    </div>
    <div class="contentsHolderOuter">
        <div class="contentsHolder">    
        <?php
            if(!empty($this->contents['displayImage'])) {
                echo '<div class="sideHeaders">';
            }
            
            if(!empty($this->contents['headerText1'])) {
                echo '<h1>'.$this->contents['headerText1'].' - RSVP</h1>';
            }
            
            if(!empty($this->contents['headerText2'])) {
                echo '<h2>'.$this->contents['headerText2'].'</h2>';
            }
            
            if(!empty($this->contents['displayImage'])) {
                echo '</div>';
                echo '<img class="adImage" src="/assets/img/competition/wire-game/addImage.jpg" alt="'.$this->facebookShare['title'].'" />';
            }
        ?>
        <?php if(!empty($this->contents['introVideo']) || !empty($this->contents['introText'])){ ?>
            <div id="fb_content_copy">
                <?php                   
                    if(!empty($this->contents['introVideo'])) {
                        echo '<iframe width="551" height="311" frameborder="0" allowfullscreen="" src="http://www.youtube.com/embed/'.$this->contents['introVideo'].'?rel=0&wmode=transparent"></iframe>';
                    }                    
                    if(!empty($this->contents['introText'])) {
                        echo '<p>'.$this->contents['introText'].'</p>';
                    }
                ?>
            </div>
         <?php } ?>
            <div id="fb_form">
                <div class="fieldsListing">                
                    <form method="post" action="/competition/<?php echo $this->facebookShare['campaign']; ?>/register?ajax=true" id="fbForm" enctype="multipart/form-data" accept-charset="utf-8">
                        <dl>
                        <?php   
                            $currentElement = 0;

                            foreach($this->formElements as $formElement)
                            {
                                if($formElement['elementVisibility'])
                                {   
                                    if($formElement['elementType'] == 'File')
                                    {
                                        echo $this->form->getElement('playerImage')->render();
                                        echo '<dd id="BrowserVisible"><input type="text" id="FileField" /><span id="fileBtnSpan" class="button">Browse</span></dd>';
                                    }
                                    else if($formElement['elementType'] == 'Email')
                                    {
                                        echo $this->form->getElement('playerEmail')->render();
                                    }
                                    else if($formElement['elementType'] == 'Textarea')
                                    {
                                        echo  '<div class="textAreaHolder">';
                                        echo $this->form->getElement($formElement['elementName'])->render();
                                        echo  '</div>';
                                    }
                                    else if($formElement['elementType'] == 'Checkbox')
                                    {
                                        echo  '<div class="checkboxHolder">';
                                        echo $this->form->getElement($formElement['elementName'])->render();
                                        echo  '</div>';
                                    }
                                    else if($formElement['elementName'] == 'question')
                                    {
                                        echo  '<div class="selectionList">';
                                        echo $this->form->getElement($formElement['elementName'])->render();
                                        echo  '</div>';                                        
                                    }
                                    else if($formElement['elementName'] == 'twitterhandle')
                                    {
                                        echo '<dd class="fullWidth">To fully experience the digital installation we’ve created for the evening we’d love you to give us your Twitter handle. Don’t worry, it’s for nothing embarrassing. And there’s a chance you could win a bottle of bubbly too.</dd>';
                                        echo $this->form->getElement($formElement['elementName'])->render();  
                                        echo '<dd class="fullWidth">Don’t have a Twitter account? <a href="https://twitter.com/signup" title="Sign up" target="_blank">Sign up</a> now and be part of the nation’s pulse.</dd>';
                                    }
                                    else
                                    {
                                        echo $this->form->getElement($formElement['elementName'])->render();
                                    }

                                    $currentElement++;
                                }
                            }
                        ?>
                            <dd class="submitWrapper">
                                <input type="hidden" name="campaignName" id="campaignName" value="<?php echo $this->facebookShare['campaignName']?>" />
                                <input type="hidden" name="campaign" id="campaign" value="<?php echo $this->facebookShare['campaign']?>" />
                                <?php echo $this->form->getElement('submitBtn')->setLabel('Submit')->render(); ?>
                            <dd>
                        </dl>
                    </form>
                </div>
            </div>
            <p id="formFooter">If you’re coming. Yay! See you on the night. <br />
                If you’re not. Boo hoo! Follow us on Twitter and watch the fun unfold. 
                <a href="https://twitter.com/tmwagency" title="@tmwagency" target="_blank">[@tmwagency]</a>
            </p>  
        </div>                
    </div>
</div>
