<div id="fb_wrapper" class="competition registerPage submit">
    <div class="header">        
        <a href="/competition/<?php echo $this->facebookShare['campaign']; ?>/register" title="">
            <img src="/assets/img/competition/logo.jpg" alt="TMW" />
        </a>
    </div>
    <div class="contentsHolderOuter">
        <div class="contentsHolder">            
        <?php
            if(!empty($this->contents['displayImage'])) {
                echo '<div class="sideHeaders">';
            }
            
            echo '<h1>Confirmation</h1>';
            
            if(!empty($this->contents['thankText'])) {
                echo '<h2>'.$this->contents['thankText'].'</h2>';
            }
            
            if(!empty($this->contents['displayImage'])) {
                echo '</div>';
                echo '<img class="adImage" src="/assets/img/competition/wire-game/addImage.jpg" alt="'.$this->facebookShare['title'].'" />';
            }
        ?>
        </div>
    </div>
</div>