<?php echo $this->doctype(); ?>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->pageTitle ?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
    
    <link rel="shortcut icon" href="/favicon.ico" />
    <?php
	// setup stylesheets
	//$this->headLink()->prependStylesheet($this->baseUrl().'/assets/css/views/competition.css');
	echo $this->headLink();
    ?>

    <script type="text/javascript" src="/assets/js/swfobject.js"></script>
    <script type="text/javascript">    
        swfobject.registerObject("scrubber", "9.0.0", "expressInstall.swf");
    </script>
    
    <script src="<?php echo $this->baseUrl(); ?>/assets/js/libs/modernizr.min.js"></script>
</head>
    
<body id="<?php echo $this->facebookShare['campaign']?>">

<?php echo $this->layout()->content; ?>

<div id="fb-root"></div>

<?php
    $this->headScript()
            ->offsetSetFile(-1, $this->baseUrl().'/assets/js/libs/jquery.min.js', 'text/javascript');
?>
    
<?php echo $this->headScript(); ?>

<?php if(!empty($this->pageGA)) { ?> 
<script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>

<script type="text/javascript">
    var pageTracker = _gat._getTracker('<?php echo $this->pageGA ?>');
    pageTracker._initData();
    pageTracker._trackPageview();
</script>
<?php } ?>

</body>
</html>