<?php
    if(!empty($this->errorMessage))
    {
        echo '<div id="message"><p>'.$this->errorMessage.'</p></div>';
    }
?>

<div class="row">
    <form  method="post">
        <table class="loginHolder">
            <tr>
                <td><label for="username"> Username: </label></td>
                <td><input type="text" name="username" /></td>
            </tr>
            <tr>
                <td><label for="password"> Password: </label></td>
                <td><input type="password" name="password" /></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="login" /></td>
            </tr>
        </table>
    </form>
</div>